import {
  FaBoxOpen,
  FaChartBar,
  FaCog,
  FaListUl,
  FaPlusSquare,
  FaShoppingCart,
  FaTags,
} from 'react-icons/fa'

export const PLATFORM_FEATURES = [
  {
    key: 'purchase-sections',
    label: 'أقسام الشراء',
    title: 'أقسام الشراء',
    description: 'أنشئ أقسام شراء ذكية لمنتجاتك، ونظّم تجربة العملاء بسهولة من أول نقرة.',
    icon: FaListUl,
    accent: '#4CDDD8',
    accentSoft: 'rgba(76, 221, 216, 0.2)',
    activeGradient: 'linear-gradient(120deg, #4eddda 0%, #3bbcc7 100%)',
    glow: 'rgba(76, 221, 216, 0.34)',
    preview: 'sections',
    chips: ['تحكم كامل', 'وقت حقيقي'],
  },
  {
    key: 'discount-coupons',
    label: 'كوبونات الخصم',
    title: 'كوبونات الخصم',
    description: 'زود مبيعاتك بكوبونات احترافية مع تفعيل فوري وتتبع أداء الخصومات لحظيًا.',
    icon: FaTags,
    accent: '#FF3E7D',
    accentSoft: 'rgba(255, 62, 125, 0.2)',
    activeGradient: 'linear-gradient(120deg, #43dbd9 0%, #5bc8cb 100%)',
    glow: 'rgba(255, 62, 125, 0.33)',
    preview: 'coupons',
    chips: ['مرن جدًا', 'نتائج أسرع'],
  },
  {
    key: 'add-sections',
    label: 'إضافة أقسام',
    title: 'إضافة أقسام',
    description: 'ابنِ هيكل متجر مرتب بإضافة أقسام جديدة وتعديلها في ثوانٍ مع انتقالات سلسة.',
    icon: FaPlusSquare,
    accent: '#A85CFF',
    accentSoft: 'rgba(168, 92, 255, 0.2)',
    activeGradient: 'linear-gradient(120deg, #44ddd9 0%, #5acccc 100%)',
    glow: 'rgba(168, 92, 255, 0.34)',
    preview: 'add-sections',
    chips: ['مرونة عالية', 'هيكلة ذكية'],
  },
  {
    key: 'add-products',
    label: 'إضافة أصناف',
    title: 'إضافة أصناف',
    description: 'أضف منتجاتك بسرعة مع صور وتفاصيل واضحة، وخلّي صفحة المنتج جاهزة فورًا.',
    icon: FaBoxOpen,
    accent: '#FFB100',
    accentSoft: 'rgba(255, 177, 0, 0.2)',
    activeGradient: 'linear-gradient(120deg, #4cded9 0%, #5dc8c8 100%)',
    glow: 'rgba(255, 177, 0, 0.34)',
    preview: 'add-products',
    chips: ['إضافة أسرع', 'عرض احترافي'],
  },
  {
    key: 'orders',
    label: 'الطلبات',
    title: 'الطلبات',
    description: 'تابع جميع الطلبات الواردة بتدفق حي، مع تنبيهات حالة الدفع والشحن بسهولة.',
    icon: FaShoppingCart,
    accent: '#07D28D',
    accentSoft: 'rgba(7, 210, 141, 0.2)',
    activeGradient: 'linear-gradient(120deg, #4adfda 0%, #5bc7c7 100%)',
    glow: 'rgba(7, 210, 141, 0.35)',
    preview: 'orders',
    chips: ['تتبع فوري', 'تنظيم عملي'],
  },
  {
    key: 'orders-control',
    label: 'تحكم بالطلبات',
    title: 'تحكم بالطلبات',
    description: 'خصص إعدادات الطلبات بالطريقة المناسبة لك، مع قواعد تشغيل مرنة وقوية.',
    icon: FaCog,
    accent: '#6A68FF',
    accentSoft: 'rgba(106, 104, 255, 0.2)',
    activeGradient: 'linear-gradient(120deg, #49dfda 0%, #67d6d6 100%)',
    glow: 'rgba(106, 104, 255, 0.35)',
    preview: 'order-control',
    chips: ['تخصيص كامل', 'تشغيل ذكي'],
  },
  {
    key: 'analytics',
    label: 'إحصائيات وتقارير',
    title: 'إحصائيات وتقارير',
    description: 'راقب نمو متجرك بالأرقام الدقيقة عبر لوحات تحليل تساعدك على اتخاذ القرار.',
    icon: FaChartBar,
    accent: '#FF8A00',
    accentSoft: 'rgba(255, 138, 0, 0.2)',
    activeGradient: 'linear-gradient(120deg, #47ddd9 0%, #67d8d9 100%)',
    glow: 'rgba(255, 138, 0, 0.36)',
    preview: 'analytics',
    chips: ['تحليل عميق', 'تقارير دقيقة'],
  },
]
