export const COUNTRIES = [
  {
    isoCode: 'SA',
    name: 'السعودية',
    dialCode: '+966',
    minLength: 9,
    maxLength: 9,
    popular: true,
  },
  {
    isoCode: 'AE',
    name: 'الإمارات',
    dialCode: '+971',
    minLength: 9,
    maxLength: 9,
    popular: true,
  },
  {
    isoCode: 'EG',
    name: 'مصر',
    dialCode: '+20',
    minLength: 10,
    maxLength: 10,
    popular: true,
  },
  {
    isoCode: 'KW',
    name: 'الكويت',
    dialCode: '+965',
    minLength: 8,
    maxLength: 8,
    popular: true,
  },
  {
    isoCode: 'QA',
    name: 'قطر',
    dialCode: '+974',
    minLength: 8,
    maxLength: 8,
    popular: true,
  },
  {
    isoCode: 'BH',
    name: 'البحرين',
    dialCode: '+973',
    minLength: 8,
    maxLength: 8,
    popular: false,
  },
  {
    isoCode: 'OM',
    name: 'عمان',
    dialCode: '+968',
    minLength: 8,
    maxLength: 8,
    popular: false,
  },
  {
    isoCode: 'JO',
    name: 'الأردن',
    dialCode: '+962',
    minLength: 9,
    maxLength: 9,
    popular: false,
  },
  {
    isoCode: 'US',
    name: 'الولايات المتحدة',
    dialCode: '+1',
    minLength: 10,
    maxLength: 10,
    popular: false,
  },
]

export const DEFAULT_COUNTRY = COUNTRIES.find((country) => country.popular)?.isoCode ?? 'SA'
