import { FaBoxes, FaChartBar, FaCreditCard, FaGlobe, FaMobileAlt, FaPaintBrush, FaSearch, FaShippingFast, FaSms, FaStar, FaTags, FaUsersCog } from 'react-icons/fa'

const CAPABILITIES = [
  {
    title: 'إدارة المخزون',
    description: 'تابع المنتجات والكميات والتنبيهات بسهولة.',
    icon: FaBoxes,
    motionType: 'boxes',
    iconColor: '#5B73FF',
    iconBg: 'rgba(91,115,255,0.15)',
    iconBorder: 'rgba(91,115,255,0.34)',
  },
  {
    title: 'تقارير وتحليلات',
    description: 'رسوم دقيقة تساعدك على اتخاذ قرار أسرع.',
    icon: FaChartBar,
    motionType: 'chart',
    iconColor: '#56A4FF',
    iconBg: 'rgba(86,164,255,0.15)',
    iconBorder: 'rgba(86,164,255,0.34)',
  },
  {
    title: 'شحن سريع ومدمج',
    description: 'ربط مباشر مع شركات الشحن وتتبع تلقائي.',
    icon: FaShippingFast,
    motionType: 'shipping',
    iconColor: '#F59B3D',
    iconBg: 'rgba(245,155,61,0.15)',
    iconBorder: 'rgba(245,155,61,0.34)',
  },
  {
    title: 'بوابات دفع متعددة',
    description: 'خيارات دفع آمنة ومتعددة لعملائك.',
    icon: FaCreditCard,
    motionType: 'payment',
    iconColor: '#2FC49F',
    iconBg: 'rgba(47,196,159,0.15)',
    iconBorder: 'rgba(47,196,159,0.34)',
  },
  {
    title: 'دومين خاص',
    description: 'اربط متجرك بنطاق احترافي يحمل هويتك.',
    icon: FaGlobe,
    motionType: 'globe',
    iconColor: '#6F8CFF',
    iconBg: 'rgba(111,140,255,0.15)',
    iconBorder: 'rgba(111,140,255,0.34)',
  },
  {
    title: 'قوالب احترافية',
    description: 'تصاميم مرنة قابلة للتخصيص الكامل.',
    icon: FaPaintBrush,
    motionType: 'paint',
    iconColor: '#FF6A8D',
    iconBg: 'rgba(255,106,141,0.15)',
    iconBorder: 'rgba(255,106,141,0.34)',
  },
  {
    title: 'تحسين محركات البحث',
    description: 'أدوات SEO جاهزة لظهور أقوى في النتائج.',
    icon: FaSearch,
    motionType: 'search',
    iconColor: '#A55BFF',
    iconBg: 'rgba(165,91,255,0.15)',
    iconBorder: 'rgba(165,91,255,0.34)',
  },
  {
    title: 'تطبيق جوال خاص',
    description: 'تجربة شراء أسهل عبر موبايل تطبيقك.',
    icon: FaMobileAlt,
    motionType: 'mobile',
    iconColor: '#22BCE3',
    iconBg: 'rgba(34,188,227,0.15)',
    iconBorder: 'rgba(34,188,227,0.34)',
  },
  {
    title: 'تنبيهات SMS',
    description: 'إشعارات ذكية لحظية لزيادة التفاعل.',
    icon: FaSms,
    motionType: 'sms',
    iconColor: '#FF6F6F',
    iconBg: 'rgba(255,111,111,0.15)',
    iconBorder: 'rgba(255,111,111,0.34)',
  },
  {
    title: 'إدارة العملاء CRM',
    description: 'تابع بيانات عملائك وتقسيمهم بسهولة.',
    icon: FaUsersCog,
    motionType: 'crm',
    iconColor: '#38B3A7',
    iconBg: 'rgba(56,179,167,0.15)',
    iconBorder: 'rgba(56,179,167,0.34)',
  },
  {
    title: 'تقييمات العملاء',
    description: 'بناء الثقة عبر عرض تقييمات المتجر.',
    icon: FaStar,
    motionType: 'star',
    iconColor: '#FFB83D',
    iconBg: 'rgba(255,184,61,0.15)',
    iconBorder: 'rgba(255,184,61,0.34)',
  },
  {
    title: 'كوبونات خصم',
    description: 'أنشئ عروضًا تسويقية لزيادة المبيعات.',
    icon: FaTags,
    motionType: 'tags',
    iconColor: '#F78B3D',
    iconBg: 'rgba(247,139,61,0.15)',
    iconBorder: 'rgba(247,139,61,0.34)',
  },
]

export { CAPABILITIES }

