export const SIGNUP_FORM_TEXT = {
  backToLogin: 'العودة لتسجيل الدخول',
  headingTop: 'أنشئ حسابك',
  headingBottom: 'الإعلاني الآن',
  intro:
    'افتح حسابك كمعلن في خطوات بسيطة، وابدأ الوصول لعملاء أكثر من خلال حملات موجهة باللغة العربية.',
  nameLabel: 'الاسم الكامل',
  namePlaceholder: 'مثال: أحمد محمد',
  emailLabel: 'البريد الإلكتروني',
  emailPlaceholder: 'أدخل البريد الإلكتروني',
  phoneLabel: 'رقم الهاتف',
  phoneFallbackPlaceholder: 'اكتب الرقم',
  passwordLabel: 'كلمة المرور',
  submit: 'تسجيل الحساب',
  emailVerificationTitle: 'تأكيد البريد الإلكتروني',
  emailVerificationDescription: 'أدخل رمز التحقق المكوّن من 6 أرقام المرسل إلى البريد الإلكتروني التالي:',
  phoneVerificationTitle: 'تأكيد رقم الهاتف',
  phoneVerificationDescription: 'أدخل رمز التحقق المكوّن من 6 أرقام المرسل إلى رقم الهاتف التالي:',
  confirmVerification: 'تأكيد',
  emailVerified: 'تم تأكيد البريد الإلكتروني بنجاح.',
  phoneVerified: 'تم تأكيد رقم الهاتف بنجاح.',
  signupSuccess: 'تم تسجيل الحساب بنجاح.',
  fieldsWarning: 'أكمل الحقول بشكل صحيح قبل المتابعة.',
  verificationWarning: 'أكمل تأكيد البريد الإلكتروني ثم رقم الهاتف لإتمام تسجيل الحساب.',
  hasAccount: 'لديك حساب بالفعل؟',
  loginNow: 'سجّل الدخول',
}
